### ISSUE TITLE
Spaces in music directory cause problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tesujimath/qlsync#1] opened 2015-05-08 23:30 UTC
```
My device gets mounted to /mnt/HTC and my music folder within that is Internal 
storage/Music. The space in that path is giving me trouble. If I simply put 
/mnt/HTC/Internal storage/Music as my music directory, I get this error:

Error: [Errno 6] No such device or address

If I enter a backslash after "Internal", then it appears to work until I 
actually try to sync a playlist, at which point I get this from the command 
line:

writing data to device (do not unplug) ...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/qlsync/engine.py", line 386, in run
    self.device.shifter.makedirs(dstDir)
  File "/usr/local/lib/python2.7/dist-packages/qlsync/shifters.py", line 38, in makedirs
    raise ShifterError(str(e))
ShifterError: Error: [Errno 38] Function not implemented: '/mnt/HTC/Internal\\ 
storage'

I also tried replacing the space with an underscore, but I again get that 
latter error.

My Python skills aren't good enough to know how to fix this myself, but I'm 
trying.
```

Original issue reported on code.google.com by `patrickv...@gmail.com` on 11 Jul 2013 at 1:20

**Comment by tesujimath** [comment] 2015-05-09 06:05
Sorry, I didn't see this issue when you raised it.  I can't reproduce the problem.  My filenames with spaces are working just fine.  Is this ancient history?  I'm closing this issue in case it is.  However, raise it again if it's still bugging you, and I'll see what I can do.

**Closed as completed by tesujimath** 2015-05-09 06:05 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
